name = "PartedArrays"
uuid = "c45eb73e-4025-11e9-27c7-23913323ccd5"
authors = ["Brian Jackson <bjack205@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
